title: Librarian
email: sids.1992@gmail.com
description: >- 
  Cause Local is best 🚀
baseurl: "" 
url: "" 
twitter_username: sids7
github_username:  biocross
host: 0.0.0.0

exclude: [localgems, vendor]
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed